import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';


export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='home_body'>
        <main>
          {data.map((ev) => (
            <Link className='card' key={ev.id} href={`/events/${ev.id}`}> 

              <div className='image'>
                <Image width={500}  height={350} alt={ev.title} src={ev.image} /> 
              </div>
  
              <div className='content'>
                <h2> {ev.title} </h2> <p> {ev.description} </p>
              </div>

            </Link>
          ))}
        </main>
      </div>
    </div>
  )
}

//fetch the json data using server side call that will pass to the home function
export async function getServerSideProps() {
  const {events_categories} = await import ('../data/data.json');
  console.log({events_categories});
  return {
    props:{
      data: events_categories,
    },
  }; 
}